#!/usr/bin/env python3
"""Build a CSV snapshot of the Summerland owner dashboard.

The live deliverable is a Google Sheet whose DASHBOARD tab is generated by
pipeline/master_sheet/DashboardSetup.gs. This script writes the same sections,
in the same top-to-bottom order, as stacked tables in one CSV (each chart is
replaced by the table that feeds it).

Usage:
    python dashboard_example/build_dashboard_example.py
"""

from __future__ import annotations

import csv
import random
from collections import defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "Summerland_Owner_Dashboard_Example.csv"

GROWER_STATEMENTS_CSV = ROOT / "data" / "grower_statements" / "grower_statements_sheet_export.csv"
EXOTICS_SUMMARY_CSV = ROOT / "pipeline" / "master_sheet" / "outputs" / "exotics_sales_summary.csv"
MARKET_CSV = ROOT / "pipeline" / "fresh_facts_scanner" / "outputs" / "hass_organic_prices_for_sheet.csv"

SNAPSHOT_DATE = date(2026, 8, 21)
LABOR_RATE = 27.0
MARKET_SIZES = [48, 60, 70, 84]

# Seasons before weekly statements were logged come from the Index Fresh annual PDFs
# in data/grower_statements/{2021,2022}/.
ANNUAL_TOTALS = {
    2021: dict(lbs_g1=540849.7, lbs_g2=16322.5, lbs_culls=13543.8, lbs_total=570716.0,
               gross=611144.03, net=503395.82, bins=630),
    2022: dict(lbs_g1=245316.4, lbs_g2=16645.1, lbs_culls=10948.5, lbs_total=272910.0,
               gross=475850.36, net=440348.86, bins=293),
}


def num(value: str) -> float:
    value = (value or "").strip().replace(",", "")
    return float(value) if value else 0.0


def week_start(d: date) -> date:
    return d - timedelta(days=d.weekday())


def usd(v: float) -> str:
    return f"${v:,.0f}"


def usd_delta(v: float) -> str:
    return f"{'+' if v >= 0 else '-'}${abs(v):,.0f}"


def rate(v: float) -> str:
    return f"${v:.2f}"


def rate_delta(v: float) -> str:
    return f"{'+' if v >= 0 else '-'}${abs(v):.2f}"


def count(v: float) -> str:
    return f"{v:,.0f}"


def count_delta(v: float) -> str:
    return f"{v:+,.0f}"


# ─── Data ────────────────────────────────────────────────────────────

def load_grower_statements() -> list[dict]:
    with GROWER_STATEMENTS_CSV.open(newline="") as f:
        return list(csv.DictReader(f))


def statement_year(r: dict) -> int:
    return datetime.strptime(r["period_start"], "%Y-%m-%d").year


def build_grower_yearly(statements: list[dict]) -> dict[int, dict]:
    by_year: dict[int, dict] = defaultdict(lambda: defaultdict(float))
    for r in statements:
        t = by_year[statement_year(r)]
        t["lbs_g1"] += num(r["lbs_grade1"])
        t["lbs_g2"] += num(r["lbs_grade2"])
        t["lbs_culls"] += num(r["lbs_culls"])
        t["lbs_total"] += num(r["lbs_total"])
        t["gross"] += num(r["gross_amount"])
        t["net"] += num(r["net_amount"])
        t["bins"] += num(r["bins_received"])
    for y, totals in ANNUAL_TOTALS.items():
        by_year[y] = dict(totals)
    for t in by_year.values():
        t["rate"] = t["gross"] / t["lbs_total"] if t["lbs_total"] else 0.0
    return dict(sorted(by_year.items()))


def build_weekly_bins(statements: list[dict], year: int) -> list[tuple[date, float]]:
    weeks: dict[date, float] = defaultdict(float)
    for r in statements:
        start = datetime.strptime(r["period_start"], "%Y-%m-%d").date()
        if start.year == year:
            weeks[week_start(start)] += num(r["bins_received"])
    return sorted(weeks.items())


def build_block_yearly(statements: list[dict], year: int) -> list[dict]:
    blocks: dict[str, dict] = defaultdict(lambda: defaultdict(float))
    for r in statements:
        if statement_year(r) != year:
            continue
        b = blocks[r["block_parcel"].strip()]
        b["bins"] += num(r["bins_received"])
        b["lbs"] += num(r["lbs_total"])
        b["net"] += num(r["net_amount"])
        b["gross"] += num(r["gross_amount"])
    rows = [
        {"block": k, "bins": v["bins"], "lbs": v["lbs"], "net": v["net"],
         "rate": v["gross"] / v["lbs"] if v["lbs"] else 0.0}
        for k, v in blocks.items()
    ]
    return sorted(rows, key=lambda r: r["net"], reverse=True)


def build_labor_weeks(year: int) -> list[tuple[date, float, float]]:
    """Illustrative labor_log rollup — the real labor form responses were not exported."""
    rng = random.Random(1532)
    base_hours = {"Harvest": 70, "Irrigation": 22, "Pruning": 14, "Weed control": 18, "Maintenance": 12}
    rows = []
    wk = week_start(date(year, 5, 25))
    while wk <= week_start(SNAPSHOT_DATE):
        harvest_season = wk <= date(year, 7, 6)
        hours = 0.0
        for activity, base in base_hours.items():
            if activity == "Harvest" and not harvest_season:
                base = 8
            hours += round(base * rng.uniform(0.7, 1.3), 1)
        rows.append((wk, round(hours * LABOR_RATE, 2), round(hours, 1)))
        wk += timedelta(days=7)
    return rows


def load_exotics() -> list[dict]:
    with EXOTICS_SUMMARY_CSV.open(newline="") as f:
        return [
            {"year": int(r["year"]), "product": r["product"], "total_lbs": num(r["total_lbs"]),
             "total_revenue": num(r["total_revenue"])}
            for r in csv.DictReader(f)
        ]


def load_market_mid() -> dict[date, dict[int, float]]:
    mid: dict[date, dict[int, float]] = defaultdict(dict)
    with MARKET_CSV.open(newline="") as f:
        for r in csv.DictReader(f):
            size = int(r["size"])
            if size in MARKET_SIZES:
                mid[datetime.strptime(r["report_date"], "%Y-%m-%d").date()][size] = num(r["hass_mid"])
    return dict(sorted(mid.items()))


# ─── CSV ─────────────────────────────────────────────────────────────

def build() -> Path:
    statements = load_grower_statements()
    yearly = build_grower_yearly(statements)
    years = list(yearly)
    this_year = years[-1]
    prior_year = this_year - 1
    cur, prior = yearly[this_year], yearly.get(prior_year)
    weekly_bins = build_weekly_bins(statements, this_year)
    blocks = build_block_yearly(statements, this_year)
    labor = build_labor_weeks(this_year)
    exotics = load_exotics()
    market = load_market_mid()

    rows: list[list] = []

    def section(title: str, *notes: str) -> None:
        if rows:
            rows.append([])
        rows.append([title])
        for n in notes:
            rows.append([n])

    labor_cost = sum(c for _, c, _ in labor)
    labor_hours = sum(h for _, _, h in labor)

    rows.append(["SUMMERLAND FARM — Avocado one-page executive summary"])
    rows.append([f"Snapshot as delivered {SNAPSHOT_DATE:%b %-d, %Y}. Live version: Google Sheets DASHBOARD tab "
                 "built by pipeline/master_sheet/DashboardSetup.gs"])

    section(f"THIS YEAR · {this_year}")
    rows.append(["Revenue (net)", "Lbs harvested", "Avg $/lb (gross)", "Bins picked", "Gross revenue", "#1 lbs"])
    rows.append([usd(cur["net"]), count(cur["lbs_total"]), rate(cur["rate"]), count(cur["bins"]),
                 usd(cur["gross"]), count(cur["lbs_g1"])])

    section("OPERATIONS / FINANCE STRIP")
    rows.append(["Latest week bins picked", "Latest week", "Labor cost (year)*", "Labor hours (year)*"])
    last_wk, last_bins = weekly_bins[-1]
    rows.append([count(last_bins), f"{last_wk:%-m/%-d/%y}", usd(labor_cost), f"{labor_hours:,.1f}"])

    section(f"YEAR-OVER-YEAR · {this_year} vs {prior_year}")
    rows.append(["Metric", str(this_year), str(prior_year), "Change"])
    for name, key, fmt, dfmt in [
        ("Revenue (net)", "net", usd, usd_delta),
        ("Lbs harvested", "lbs_total", count, count_delta),
        ("Bins picked", "bins", count, count_delta),
        ("Avg $/lb (gross)", "rate", rate, rate_delta),
    ]:
        rows.append([name, fmt(cur[key]), fmt(prior[key]), dfmt(cur[key] - prior[key])])

    section("HISTORICAL TRENDS — BY YEAR", "(chart: Net $ by year)")
    rows.append(["Year", "Net $", "Gross $", "Lbs", "Bins", "Avg $/lb (gross)"])
    for y, t in yearly.items():
        rows.append([y, usd(t["net"]), usd(t["gross"]), count(t["lbs_total"]), count(t["bins"]), rate(t["rate"])])

    section(f"GRADE MIX · {this_year}", "(chart: donut)")
    rows.append(["Grade", "Lbs", "Share"])
    for name, key in [("Grade #1", "lbs_g1"), ("Grade #2", "lbs_g2"), ("Culls", "lbs_culls")]:
        rows.append([name, count(cur[key]), f"{cur[key] / cur['lbs_total']:.1%}"])

    section(f"WEEKLY HARVEST / BINS PICKED · {this_year}", "(chart: line)")
    rows.append(["Week of", "Bins"])
    for wk, b in weekly_bins:
        rows.append([f"{wk:%-m/%-d/%y}", count(b)])

    section(f"BLOCK PERFORMANCE — YEARLY · {this_year}",
            "$/lb (gross) = gross ÷ lbs. Net $ is after Index Fresh charges.")
    rows.append(["Block", "Bins", "Lbs", "Net $", "$/lb (gross)"])
    for b in blocks:
        rows.append([b["block"], count(b["bins"]), count(b["lbs"]), usd(b["net"]), rate(b["rate"])])
    rows.append(["Total", count(sum(b["bins"] for b in blocks)), count(sum(b["lbs"] for b in blocks)),
                 usd(sum(b["net"] for b in blocks)), ""])

    section(f"LABOR COST BY WEEK · {this_year}*", f"Est. cost = hours × ${LABOR_RATE:.0f}/hr (all activities)")
    rows.append(["Week of", "Labor $", "Hours"])
    for wk, cost, hours in labor:
        rows.append([f"{wk:%-m/%-d/%y}", usd(cost), f"{hours:,.1f}"])

    latest = list(market)[-1]
    section("MARKET — HASS MID $/LB (FRESH FACTS)", "(chart: line by size) · auto-imported from Gmail reports")
    rows.append(["Latest report", "Size 48", "Size 60", "Size 70", "Size 84", "Reports"])
    rows.append([f"{latest:%-m/%-d/%y}"] + [rate(market[latest][s]) if s in market[latest] else ""
                                           for s in MARKET_SIZES] + [len(market)])
    rows.append([])
    rows.append(["Report date"] + [f"Size {s}" for s in MARKET_SIZES])
    for d, by_size in market.items():
        rows.append([f"{d:%-m/%-d/%y}"] + [rate(by_size[s]) if s in by_size else "" for s in MARKET_SIZES])

    is_passion = lambda r: "passion" in r["product"].lower()  # noqa: E731
    non_avo = [r for r in exotics if r["product"] != "Avocados"]
    section("EXOTICS & PASSIONFRUIT")
    rows.append(["Passionfruit $ (all years)", "Exotics total $", "Passionfruit lbs"])
    rows.append([usd(sum(r["total_revenue"] for r in exotics if is_passion(r))),
                 usd(sum(r["total_revenue"] for r in non_avo)),
                 count(sum(r["total_lbs"] for r in exotics if is_passion(r)))])

    section("PASSIONFRUIT REVENUE BY YEAR", "(chart: column)")
    rows.append(["Year", "Revenue", "Lbs"])
    pf: dict[int, list[float]] = defaultdict(lambda: [0.0, 0.0])
    for r in exotics:
        if is_passion(r):
            pf[r["year"]][0] += r["total_revenue"]
            pf[r["year"]][1] += r["total_lbs"]
    for y, (rev, lbs) in sorted(pf.items()):
        rows.append([y, usd(rev), count(lbs)])

    section("EXOTICS BY PRODUCT (ALL YEARS)", "(chart: bar)")
    rows.append(["Product", "Revenue"])
    by_product: dict[str, float] = defaultdict(float)
    for r in non_avo:
        by_product[r["product"]] += r["total_revenue"]
    for product, rev in sorted(by_product.items(), key=lambda kv: kv[1], reverse=True):
        rows.append([product, usd(rev)])

    exotic_year = max(r["year"] for r in exotics)
    section(f"FRUIT SALES · {exotic_year}", "Live sheet: Summerland Dashboard → Exotics year switches this table")
    rows.append(["Fruit", "Revenue"])
    fruit = sorted((r for r in non_avo if r["year"] == exotic_year), key=lambda r: r["total_revenue"], reverse=True)
    for r in fruit:
        rows.append([r["product"], usd(r["total_revenue"])])
    rows.append(["Total", usd(sum(r["total_revenue"] for r in fruit))])

    section("NOTES")
    rows.append(["* Labor figures are illustrative — the crew's labor form responses were not exported. "
                 "All avocado, block, market and exotics numbers are real master-sheet data."])
    rows.append(["Avocado years 2023+ are rolled up from weekly Index Fresh grower statements; "
                 "2021–2022 come from the annual statement PDFs."])

    width = max(len(r) for r in rows)
    with OUT.open("w", newline="") as f:
        csv.writer(f).writerows(r + [""] * (width - len(r)) for r in rows)
    return OUT


if __name__ == "__main__":
    print(f"Wrote {build()}")
